# Taps
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/dupes'

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

# Install ZSH
brew 'zsh'
brew 'zsh-completions'

# Install GNU core utilities (those that come with OS X are outdated)
brew 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'

# Install Bash 4
brew 'bash'

# Install more recent versions of some OS X tools
brew 'homebrew/dupes/grep'

# Install Binaries
brew 'tmux'
brew 'awscli'
brew 'git'
brew 'hub'
brew 'tree'
brew 'mackup'
brew 'trash'
brew 'wget'
brew 'm-cli'

# Development
brew 'python'
brew 'ruby'
brew 'node'
brew 'pyenv'
brew 'rbenv'

# Apps
cask 'ngrok'
cask 'aerial'
cask 'atom'
cask 'cheatsheet'
cask 'dash'
cask 'dropbox'
cask 'docker'
cask 'evernote'
cask 'goofy'
cask 'google-chrome'
cask 'macdown'
cask 'iterm2'
cask 'pycharm'
cask 'screenhero'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'textual'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'karabiner'

# Fonts
cask 'font-sauce-code-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
